
server:
  port: 8888
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/qhdfl?characterEncoding=utf-8
  thymeleaf:
    cache: false
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password: 123456
    timeout: 1200
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
  resources:
    static-locations:

mybatis:
  type-aliases-package: garin.javaredis.model
  mapper-locations: classpath:mybatis/mappers/*.xml

logging:
  path: ${application.logfiles.path}
